from . import (
    bca_sede,
    res_partner,
    res_partner_agente_aseg,
    product_template,
    conducto,
    factor_pca,
    poliza,
    poliza_beneficiario,
    poliza_cambio_agente,
    recibo,
    bitacora,
    dashboard,
    hr_applicant,
    crm_lead,
)
