from . import (
    test_poliza,
    test_poliza_vida,
    test_poliza_gmm,
    test_poliza_coberturas,
    test_cobranza_fifo,
    test_pca_metlife,
    test_inmutabilidad,
    test_record_rules,
    test_bca_sede,
    test_hr_applicant,
    test_crm_lead,
    test_views_xml,
    test_parsers,
    test_carga_portafolio,
    test_reportes,
    test_dashboard,
)
